# To change this licence header, chose Licence Headers in Project Properties
# To change this template file, choose Tools | Templates
# and open the templati in the editor


#Database Configuration
url = jdbc:mysql://localhost:3306/bazaseminarski
username = root
password =