/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import koordinator.Koordinator;
import mod.ModPredmet;

/**
 *
 * @author Win 10
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelUlogovani = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjekti = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemStudentDodaj = new javax.swing.JMenuItem();
        jMenuItemStudentPretrazi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemObrisiPredmet = new javax.swing.JMenuItem();
        jMenuItemPredmetPretrazi = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemDodajAngazovanje = new javax.swing.JMenuItem();
        jMenuItemPretraziAngazovanje = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Zdravo");

        jTableProjekti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProjekti);

        jMenu1.setText("Student");

        jMenuItemStudentDodaj.setText("Kreiraj");
        jMenuItemStudentDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudentDodajActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemStudentDodaj);

        jMenuItemStudentPretrazi.setText("Pretrazi");
        jMenuItemStudentPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudentPretraziActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemStudentPretrazi);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Predmet");

        jMenuItemObrisiPredmet.setText("Obrisi");
        jMenuItemObrisiPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemObrisiPredmetActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemObrisiPredmet);

        jMenuItemPredmetPretrazi.setText("Pretrazi");
        jMenuItemPredmetPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPredmetPretraziActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPredmetPretrazi);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Angazovanje");

        jMenuItemDodajAngazovanje.setText("Dodaj");
        jMenu4.add(jMenuItemDodajAngazovanje);

        jMenuItemPretraziAngazovanje.setText("Pretrazi");
        jMenu4.add(jMenuItemPretraziAngazovanje);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUlogovani))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUlogovani))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemObrisiPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemObrisiPredmetActionPerformed
        Koordinator.getInstance().otvoriPrikazPredmetaFormu(ModPredmet.obrisi);
    }//GEN-LAST:event_jMenuItemObrisiPredmetActionPerformed

    private void jMenuItemStudentPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentPretraziActionPerformed
        Koordinator.getInstance().otvoriPrikazStudentaFormu();
    }//GEN-LAST:event_jMenuItemStudentPretraziActionPerformed

    private void jMenuItemPredmetPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPredmetPretraziActionPerformed
        Koordinator.getInstance().otvoriPrikazPredmetaFormu(ModPredmet.pronadji);
    }//GEN-LAST:event_jMenuItemPredmetPretraziActionPerformed

    private void jMenuItemStudentDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentDodajActionPerformed
        Koordinator.getInstance().otvoriDodajStudentaFormu();
    }//GEN-LAST:event_jMenuItemStudentDodajActionPerformed

    public JLabel getjLabelUlogovani() {
        return jLabelUlogovani;
    }

    public void setjLabelUlogovani(JLabel jLabelUlogovani) {
        this.jLabelUlogovani = jLabelUlogovani;
    }

   

    public JTable getjTableProjekti() {
        return jTableProjekti;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUlogovani;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDodajAngazovanje;
    private javax.swing.JMenuItem jMenuItemObrisiPredmet;
    private javax.swing.JMenuItem jMenuItemPredmetPretrazi;
    private javax.swing.JMenuItem jMenuItemPretraziAngazovanje;
    private javax.swing.JMenuItem jMenuItemStudentDodaj;
    private javax.swing.JMenuItem jMenuItemStudentPretrazi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProjekti;
    // End of variables declaration//GEN-END:variables

    
}
