/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme.predmet;

import controller.Controller;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import mod.ModPredmet;
import model.Predmet;

/**
 *
 * @author Win 10
 */
public class ObrisiPredmetForma extends javax.swing.JDialog {
    private Predmet p;
    private PrikazPredmetaForma ppf;
    /**
     * Creates new form ObrisiPredmetForma
     */
    public ObrisiPredmetForma(java.awt.Dialog parent, boolean modal, Predmet p) {
        super(parent, modal);
        initComponents();
        this.p = p;
        this.ppf = (PrikazPredmetaForma) parent;
        if(p == null){
            JOptionPane.showMessageDialog(this, "Систем није успео да учита предмет");
        }else{
             JOptionPane.showMessageDialog(this, "Систем је учитао предмет");
        }
        setLocationRelativeTo(null);
        jTextFieldESPB.setEditable(false);
        jTextFieldNaziv.setEditable(false);
        jTextFieldObavezan.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldESPB = new javax.swing.JTextField();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldObavezan = new javax.swing.JTextField();
        jButtonObrisi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jLabel1.setText("ESPB");

        jLabel2.setText("Naziv");

        jLabel3.setText("Obavezan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jButtonObrisi)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldObavezan)
                            .addComponent(jTextFieldESPB))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonObrisi))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldESPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldObavezan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
               try{
                 Controller.getInstance().deletePredmet(p);
                 JOptionPane.showMessageDialog(this, "Систем је обрисао предмет", "Успех", JOptionPane.INFORMATION_MESSAGE);
                 ppf.pripremiFormu();
                 this.dispose();
                }catch(Exception ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Систем не може да обрише предмет", "Грешка", JOptionPane.INFORMATION_MESSAGE);
                }
              
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldESPB;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldObavezan;
    // End of variables declaration//GEN-END:variables

    void pripremiFormu(ModPredmet modPredmet) {
        switch (modPredmet) {
            case obrisi:
                
                jTextFieldNaziv.setText(p.getNaziv());
                jTextFieldObavezan.setText(p.isObavezan() ? "da":"ne");
                jTextFieldESPB.setText(p.getEspb() + " ");
                jButtonObrisi.setVisible(true);
                break;
            case pronadji:
                jTextFieldESPB.setText(p.getEspb() + " ");
                jTextFieldNaziv.setText(p.getNaziv());
                jTextFieldObavezan.setText(p.isObavezan() ? "da":"ne");
                jButtonObrisi.setVisible(false);
                break;
            default:
                throw new AssertionError();
        }
    }
}
