/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme.predmet;

import forme.tableModel.ModelTabelePredmet;
import java.util.List;
import javax.swing.JOptionPane;
import mod.ModPredmet;
import model.Predmet;

/**
 *
 * @author Win 10
 */
public class PrikazPredmetaForma extends javax.swing.JDialog {
    private PrikazPredmetaForma ppf;
    /**
     * Creates new form PrikazPredmetaForma
     */
    public PrikazPredmetaForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pripremiFormu();
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNaziv = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonResetuj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePredmeti = new javax.swing.JTable();
        jButtonDetalji = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEspb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Da", "Ne", " " }));
        jComboBox1.setSelectedIndex(-1);

        jLabel4.setText("Obavezan");

        jButtonPretrazi.setText("Pretrazi");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jButtonResetuj.setText("Resetuj");
        jButtonResetuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetujActionPerformed(evt);
            }
        });

        jTablePredmeti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePredmeti);

        jButtonDetalji.setText("Detalji");
        jButtonDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiActionPerformed(evt);
            }
        });

        jLabel1.setText("espb");

        jLabel2.setText("PRETRAGA");

        jLabel3.setText("Naziv");

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEspb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, 0, 120, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPretrazi)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonResetuj)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldEspb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonPretrazi)
                    .addComponent(jButtonResetuj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDetalji)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonObrisi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        
        int espb;
            if(jTextFieldEspb.getText() == null || jTextFieldEspb.getText().isEmpty())
                espb = 0;
            else 
                espb = Integer.valueOf(jTextFieldEspb.getText()); 
             String naziv = jTextFieldNaziv.getText(); 
             ModelTabelePredmet mtp = (ModelTabelePredmet) jTablePredmeti.getModel();
             if(jComboBox1.getSelectedIndex() == -1 || jComboBox1.getSelectedIndex() == 2)
             mtp.pretraziNoBool(espb, naziv);
             else{
             boolean obavezan = jComboBox1.getSelectedItem().equals("Da");
             mtp.findPredmet(espb,naziv,obavezan);    
              }
             if(mtp.getLista().size() == 0)
                JOptionPane.showMessageDialog(this, "Систем не може да нађе предмете по задатим вредностима");
             else
                JOptionPane.showMessageDialog(this, "Систем је нашао предмете по задатим вредностима");

    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonResetujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetujActionPerformed
        pripremiFormu();
    }//GEN-LAST:event_jButtonResetujActionPerformed

    private void jButtonDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiActionPerformed
        
          int red = jTablePredmeti.getSelectedRow();
                if(red == -1){
                     JOptionPane.showMessageDialog(this, "Изаберите предмет из табеле","Грешка", JOptionPane.INFORMATION_MESSAGE);
                     return;
                }
                
                ModelTabelePredmet mtp = (ModelTabelePredmet) jTablePredmeti.getModel();
                Predmet p = mtp.getLista().get(red);
               
                ObrisiPredmetForma opf = new ObrisiPredmetForma(null, true,p);
                opf.pripremiFormu(ModPredmet.pronadji);
                opf.setVisible(true);
    }//GEN-LAST:event_jButtonDetaljiActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        
        int red = jTablePredmeti.getSelectedRow();
                if(red == -1){
                     JOptionPane.showMessageDialog(this, "Изаберите предмет из табеле","Грешка", JOptionPane.INFORMATION_MESSAGE);
                     return;
                }
                
                ModelTabelePredmet mtp = (ModelTabelePredmet) jTablePredmeti.getModel();
                Predmet p = mtp.getLista().get(red);
               
                ObrisiPredmetForma opf = new ObrisiPredmetForma(this, true, p);
                opf.pripremiFormu(ModPredmet.obrisi);
                opf.setVisible(true);
                
    }//GEN-LAST:event_jButtonObrisiActionPerformed

   

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonResetuj;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePredmeti;
    private javax.swing.JTextField jTextFieldEspb;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    public void pripremiFormu() {
        List<Predmet> predmeti = controller.Controller.getInstance().loadListPredmeti();
        ModelTabelePredmet mtp = new ModelTabelePredmet(predmeti);
        jTablePredmeti.setModel(mtp);
    }

    public void setMode(ModPredmet modPredmet) {
        switch (modPredmet) {
            case pronadji:
                jButtonDetalji.setVisible(true);
                jButtonObrisi.setVisible(false);
                break;
            case obrisi:
                jButtonDetalji.setVisible(false);
                jButtonObrisi.setVisible(true);
                break;
            default:
                throw new AssertionError();
        }
    }
}
