/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;
import forme.angazovanje.DodajAngazovanjeForma;
import forme.angazovanje.PrikazAngazovanjaForma;

import forme.predmet.PrikazPredmetaForma;
import forme.student.DodajStudentaForma;
import forme.student.PrikazStudenataForma;
import forme.tableModel.ModelTabeleAngazovanja;
import forme.tableModel.ModelTabeleProjekti;
import forme.tableModel.ModelTabeleStudent;
import java.awt.Frame;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import mod.ModPredmet;
import mod.ModProjekat;
import model.Angazovanje;
import model.Predmet;
import model.Profesor;
import model.Projekat;
import model.Student;
/**
 *
 * @author Win 10
 */
public class GlavnaForma extends javax.swing.JDialog {
    
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        populateTable();
        jLabel8.setText(controller.Controller.ulogovaniProfesor.getIme());
        populateComboBoxes();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjekti = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jlabelUlogovani = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelProfesor = new javax.swing.JLabel();
        jComboBoxProfesorDodaj = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxStudent = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPredmetPretrazi = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTema = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBrojPoena = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonResetuj = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableStudenti = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxProfesorPretrazi = new javax.swing.JComboBox<>();
        jComboBoxPredmetDodaj = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemStudentDodaj = new javax.swing.JMenuItem();
        jMenuItemStudentPretrazi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemObrisiPredmet = new javax.swing.JMenuItem();
        jMenuItemPredmetPretrazi = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemPretraziAngazovanje = new javax.swing.JMenuItem();
        jMenuItemDodajAngazovanje = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableProjekti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProjekti);

        jLabel1.setText("Zdravo");

        jLabel2.setText("Profesor");

        jButton1.setText("Dodaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Student");

        jLabel4.setText("Predmet");

        jComboBoxPredmetPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPredmetPretraziActionPerformed(evt);
            }
        });

        jLabel5.setText("Tema");

        jLabel6.setText("Broj Poena");

        jLabel7.setText("Rok Predaje");

        jButtonPretrazi.setText("Pretrazi");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jButtonResetuj.setText("Resetuj");
        jButtonResetuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetujActionPerformed(evt);
            }
        });

        jButton2.setText("Izmeni");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTableStudenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableStudenti);

        jLabel9.setText("Studenti");

        jLabel10.setText("Profesor");

        jComboBoxPredmetDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPredmetDodajActionPerformed(evt);
            }
        });

        jLabel11.setText("Predmet");

        jLabel12.setText("Projekti");

        jMenu1.setText("Student");

        jMenuItemStudentDodaj.setText("Kreiraj");
        jMenuItemStudentDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudentDodajActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemStudentDodaj);

        jMenuItemStudentPretrazi.setText("Pretrazi");
        jMenuItemStudentPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudentPretraziActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemStudentPretrazi);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Predmet");

        jMenuItemObrisiPredmet.setText("Obrisi");
        jMenuItemObrisiPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemObrisiPredmetActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemObrisiPredmet);

        jMenuItemPredmetPretrazi.setText("Pretrazi");
        jMenuItemPredmetPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPredmetPretraziActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPredmetPretrazi);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Angazovanje");

        jMenuItemPretraziAngazovanje.setText("Pretrazi");
        jMenuItemPretraziAngazovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziAngazovanjeActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemPretraziAngazovanje);

        jMenuItemDodajAngazovanje.setText("Dodaj");
        jMenuItemDodajAngazovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajAngazovanjeActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemDodajAngazovanje);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                                .addComponent(jButtonPretrazi)
                                .addGap(108, 108, 108)
                                .addComponent(jButtonResetuj)
                                .addGap(297, 297, 297))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jlabelUlogovani)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelProfesor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldTema)
                                            .addComponent(jComboBoxProfesorPretrazi, 0, 156, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(jLabel3)
                                                .addGap(11, 11, 11))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldBrojPoena, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxPredmetPretrazi, 0, 150, Short.MAX_VALUE)
                                            .addComponent(jTextFieldDatum))))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(216, 216, 216)
                                        .addComponent(jLabel11)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxProfesorDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxPredmetDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabelProfesor)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPredmetPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxProfesorPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldBrojPoena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonPretrazi)
                                    .addComponent(jButtonResetuj)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jlabelUlogovani)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxProfesorDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxPredmetDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getjTableStudenti() {
        return jTableStudenti;
    }
    
    
    private void jMenuItemStudentDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentDodajActionPerformed
       DodajStudentaForma dsf = new DodajStudentaForma(null,true,null,this);
       dsf.setVisible(true);
    }//GEN-LAST:event_jMenuItemStudentDodajActionPerformed

    private void jMenuItemStudentPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentPretraziActionPerformed
           PrikazStudenataForma psf = new PrikazStudenataForma(null, true);
           psf.setVisible(true);
    }//GEN-LAST:event_jMenuItemStudentPretraziActionPerformed

    private void jMenuItemObrisiPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemObrisiPredmetActionPerformed
           PrikazPredmetaForma ppf = new PrikazPredmetaForma(null, true);
           ppf.setMode(ModPredmet.obrisi);
           ppf.setVisible(true);
    }//GEN-LAST:event_jMenuItemObrisiPredmetActionPerformed

    private void jMenuItemPredmetPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPredmetPretraziActionPerformed
           PrikazPredmetaForma ppf = new PrikazPredmetaForma(null, true);
           ppf.setMode(ModPredmet.pronadji);
            ppf.setVisible(true);
    }//GEN-LAST:event_jMenuItemPredmetPretraziActionPerformed

    private void jMenuItemPretraziAngazovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziAngazovanjeActionPerformed
        PrikazAngazovanjaForma paf = new PrikazAngazovanjaForma(null, true);
        paf.setVisible(true);
    }//GEN-LAST:event_jMenuItemPretraziAngazovanjeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Profesor p = (Profesor) jComboBoxProfesorDodaj.getSelectedItem();
       Predmet pred = (Predmet) jComboBoxPredmetDodaj.getSelectedItem();
            int[] redStudent = jTableStudenti.getSelectedRows();
            
            ModelTabeleStudent mts = (ModelTabeleStudent) jTableStudenti.getModel();
            List<Student> listaStudenta = mts.getLista();
            List<Student> selektovaniStudenti = new ArrayList<>();
            for (int red : redStudent) {
                Student s = listaStudenta.get(red);
                selektovaniStudenti.add(s);
            }
             if(selektovaniStudenti.isEmpty()){
             JOptionPane.showMessageDialog(this, "На пројекту мора бити ангажован бар један студент");
             return;
         }
            new DodajProjekatForma(null, true, this, (ArrayList<Student>) selektovaniStudenti, pred, p, ModProjekat.dodaj).setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxPredmetPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPredmetPretraziActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPredmetPretraziActionPerformed

    private void jButtonResetujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetujActionPerformed
        
        populateTable();
        
    }//GEN-LAST:event_jButtonResetujActionPerformed

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
 
    Profesor prof;
    int ind = jComboBoxProfesorPretrazi.getSelectedIndex();
    
    ArrayList<Profesor> profesori = (ArrayList<Profesor>) controller.Controller.getInstance().loadListProfesor();
        
    if(ind == -1){
       prof = null;
    }else{
         prof = profesori.get(ind);
    }
    
    Predmet pred = (Predmet) jComboBoxPredmetPretrazi.getSelectedItem();
    Student stud = (Student) jComboBoxStudent.getSelectedItem();
    String tema = jTextFieldTema.getText().trim();
    String datum = jTextFieldDatum.getText().trim();
    java.util.Date Datum = null;

    // Parsiranje datuma ako je polje popunjeno
    if (!datum.isEmpty()) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd");
        try {
            Datum = sdf.parse(datum);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Грешка у датуму");
            return;  // Prekida ako datum nije ispravan
        }
    }
    
    // Parsiranje broja poena ako je polje popunjeno
    Integer brojPoena = null;
    if (!jTextFieldBrojPoena.getText().trim().isEmpty()) {
        try {
            brojPoena = Integer.parseInt(jTextFieldBrojPoena.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Грешка у уносу броја поена");
            return;  // Prekida ako broj poena nije ispravan
        }
    }
    
    // Poziv metode za pretragu
    ModelTabeleProjekti mtp = (ModelTabeleProjekti) jTableProjekti.getModel();
     System.out.println("Unete vrednosti:");
    System.out.println("Tema: " + tema);
    System.out.println("Datum: " + datum);
    System.out.println("Broj poena: " + brojPoena);
    System.out.println("Profesor: " + prof);
    System.out.println("Predmet: " + pred);
    System.out.println("student: " + stud);
    
    
    mtp.pretrazi(prof, pred, stud, tema.isEmpty() ? null : tema, Datum, brojPoena);
    
    // Ažuriranje modela tabele
    if (mtp.getLista().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Систем не може да нађе пројекте по задатим вредностима");
    } else {
        JOptionPane.showMessageDialog(this, "Систем је нашао пројекте по задатим вредностима");
        }
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
          int[] redProjekat = jTableProjekti.getSelectedRows();
          if(redProjekat.length == 0){
               JOptionPane.showMessageDialog(this, "Морате изабрати бар један пројекат", "Неуспех", JOptionPane.INFORMATION_MESSAGE);
               return;
          }
          ModelTabeleProjekti mtp = (ModelTabeleProjekti) jTableProjekti.getModel();
         
          List<Projekat> listaProjekata = mtp.getLista();
        
          List<Projekat> selektovaniProjekti = new ArrayList<>();
      
            for (int red : redProjekat) {
                Projekat p = listaProjekata.get(red);
                selektovaniProjekti.add(p);
            }
            //System.out.println(selektovaniProjekti);
            new DodajProjekatForma(null, true, (ArrayList<Projekat>) selektovaniProjekti, ModProjekat.izmeni).setVisible(true);
           
             
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxPredmetDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPredmetDodajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPredmetDodajActionPerformed

    private void jMenuItemDodajAngazovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajAngazovanjeActionPerformed
       
        new DodajAngazovanjeForma(null, true, null).setVisible(true);
        
    }//GEN-LAST:event_jMenuItemDodajAngazovanjeActionPerformed

    public JTable getjTableProjekti() {
        return jTableProjekti;
    }

    public void osveziStudentTabelu(){
        ArrayList<Student> studenti = (ArrayList<Student>) controller.Controller.getInstance().loadListStudenti();
        ModelTabeleStudent mts = new ModelTabeleStudent(studenti);
        jTableStudenti.setModel(mts);
    }
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonResetuj;
    private javax.swing.JComboBox<Predmet> jComboBoxPredmetDodaj;
    private javax.swing.JComboBox<Predmet> jComboBoxPredmetPretrazi;
    private javax.swing.JComboBox<Profesor> jComboBoxProfesorDodaj;
    private javax.swing.JComboBox<Profesor> jComboBoxProfesorPretrazi;
    private javax.swing.JComboBox<Student> jComboBoxStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelProfesor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDodajAngazovanje;
    private javax.swing.JMenuItem jMenuItemObrisiPredmet;
    private javax.swing.JMenuItem jMenuItemPredmetPretrazi;
    private javax.swing.JMenuItem jMenuItemPretraziAngazovanje;
    private javax.swing.JMenuItem jMenuItemStudentDodaj;
    private javax.swing.JMenuItem jMenuItemStudentPretrazi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableProjekti;
    private javax.swing.JTable jTableStudenti;
    private javax.swing.JTextField jTextFieldBrojPoena;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldTema;
    private javax.swing.JLabel jlabelUlogovani;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
        List<Projekat> lista = controller.Controller.getInstance().loadListProjekti();
        ModelTabeleProjekti mtp = new ModelTabeleProjekti(lista);
        jTableProjekti.setModel(mtp);
        
        
        
        
        List<Student> studenti = controller.Controller.getInstance().loadListStudenti();
        ModelTabeleStudent mts = new ModelTabeleStudent(studenti);
        jTableStudenti.setModel(mts);
    }

   

    

    private void populateComboBoxes() {
        
         List<Predmet> predmeti = controller.Controller.getInstance().loadListPredmeti();
         
        for (Predmet p : predmeti) {
            jComboBoxPredmetPretrazi.addItem(p);
        }
        
         for (Predmet p : predmeti) {
            jComboBoxPredmetDodaj.addItem(p);
        }
        List<Profesor> profesori = controller.Controller.getInstance().loadListProfesor();
        for (Profesor p : profesori) {
            jComboBoxProfesorDodaj.addItem(p);
        }
        
        for (Profesor p : profesori) {
            jComboBoxProfesorPretrazi.addItem(p);
        }
        
        List<Student> studenti = controller.Controller.getInstance().loadListStudenti();
        for (Student s : studenti) {
            jComboBoxStudent.addItem(s);
        }
        
        jComboBoxPredmetPretrazi.addItem(null);
        jComboBoxStudent.addItem(null);
        jComboBoxProfesorPretrazi.addItem(null);
        
    }
}
